import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../global.css';
import '../reset.css';
import StyledComponentsRegistry from '../styledRegistry';
import { MainLayout } from '@/components/UI/layouts/MainLayout/MainLayout';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <MainLayout>{children}</MainLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
