import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../reset.css';
import '../global.css';
import StyledComponentsRegistry from '../styledRegistry';
import { MainLayout } from '@/components/UI/layouts/MainLayout/MainLayout';
import { AuthProvider } from '@/context/AuthContext';
import userImg from '@/assets/img/JohnDoe.jpeg';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <AuthProvider
            auth={{
              isAuth: true,
              userInfo: {
                id: 'john_doe',
                name: 'John Doe',
                userImg: userImg.src,
              },
            }}
          >
            <MainLayout>{children}</MainLayout>
          </AuthProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
